### ISSUE TITLE
Add iframe and display code block too

### ISSUE THREAD

**Issue by znck** [egoist/docute-iframe#2]
In most cases displayed code & demo code is same. This would prevent code duplication in demos.

```
````vue+demo

<div id="app-1"> {{ foo }} </div>

<script> new App ({ el: '#app-1', data: () => ({ foo: 'Hello' }) })</script>

`` ``
```

**Comment by egoist** [comment]
Simply return`originalCodeBlock + iframe`? It would be awesome to display a tab to toggle between code and demo 😄

**Comment by znck** [comment]
```vue+<demo|toggle>``` 😛

**Comment by znck** [comment]
Don't use ````vue+xxxx

PHPStorm does highlight code then :disappointed:

**Comment by egoist** [comment]
Yep, I think this could be a global option

**Comment by znck** [comment]
I presume it can be overridden in markdown front matter!

**Comment by egoist** [comment]
I've made it display source code above the demo by default, to keep it simple I think the `toggle` feature could be implemented in another plugin if needed.
